version: '2'

services:
  plexamp:
    container_name: plexamp
    build:
      context: ./
    image: plexamp:4.2.2-b5
    devices:
      - "/dev/snd:/dev/snd"
    network_mode: host
    restart: unless-stopped
