version: '2'

services:
  plexamp:
    container_name: plexamp
    build:
      context: ./
    image: plexamp:v4.2.2-beta.5
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      #- "./server.json:/root/.config/Plexamp/server.json"
    network_mode: host
    restart: unless-stopped
